# site settings
title: Chris Lawson
subtitle: Student
description: Atascadero High School student with plans to study Computer Engineering at a 4-year university.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://chris2fourlaw.me # the base hostname & protocol for your site
author: Chris Lawson
google_analytics: UA-131464362-1

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
email: contact@chris2fourlaw.me
facebook_url: https://www.facebook.com/chris.lawson.75839923
github_url: https://github.com/Chris2fourlaw
instagram_url: https://www.instagram.com/chris2fourlaw
linkedin_url: https://www.linkedin.com/in/christopher-lawson-746265182/
spotify_url: https://open.spotify.com/user/chris2fourlaw

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
