title: Chris Lawson
description: Student Aspiring Computer Engineering
google_analytics: UA-131464362-1
google_adsense: ca-pub-4732857570960208
theme: jekyll-theme-cayman

url: "https://chris2fourlaw.me"
plugins:
  - jekyll-sitemap
