title: Chris Lawson
description: Student Aspiring Computer Engineering
google_analytics: UA-131464362-1
theme: jekyll-theme-cayman

url: "https://chris2fourlaw.me"
plugins:
  - jekyll-sitemap

# Social Media
github_username: Chris2fourlaw
instagram_username: chris2fourlaw